<?php
/**
 * Copyright (c) 2018 acidgreen. All Rights Reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 * Created by Tony Trinh
 * Project: Peppermayo Cloud
 * Date: 7/12/2018
 * Time: 4:3:8
 * Last modified: 7/12/18 4:02 PM
 *
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
    <?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                    <span><?= $block->escapeHtml($currentCurrencyCode) ?> - <?= @$block->escapeHtml($currencies[$currentCurrencyCode]) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($currencies as $_code => $_name): ?>
                    <?php if ($_code != $currentCurrencyCode): ?>
                        <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                            <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?= $block->escapeHtml($_code) ?> - <?= $block->escapeHtml($_name) ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
