<?php
/**
 *  Copyright © 2017 Magento. All rights reserved.
 *  See COPYING.txt for license details.
 */
namespace Acidgreen\ContactUs\Controller\Adminhtml\Index;
use Magento\Backend\App\Action;

/**
 * Class Index
 * @package Unit6\ComputerGames\Controller\Adminhtml\Game
 */
class Index extends Action
{
    /**
     * @return \Magento\Framework\View\Result\Page
     */
    public function execute()
    {
        return $this->resultFactory->create('page');
    }

    /**
     * @return bool
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Acidgreen_ContactUs::grid');

    }
    
    /**
     * Link must be generated by server side
     * It's only for education purpose!
     *
     * @return bool
     */
    public function _processUrlKeys()
    {
        return true;
    }
}