<?php
    $imgLink = null;

    if($block->getData("button_link_1") && empty($block->getData("button_1"))){
        $imgLink = $block->getData("button_link_1") ;
    }
?>

<section class="row  column-block one-column-block">
    <div class="col col-xs-12">
        <div class="slide image_banner_wrap">
            <?php if($imgLink) : ?>
                <a  href="<?= $block->getData("button_link_1") ?>">
             <?php endif; ?>
                <img class="hidden-xs" src="<?= $block->getData("banner_desktop") ?>" alt="<?= $block->getData("banner_name") ?>" />
                <img class="visible-xs-block" src="<?= $block->getData("banner_mobile") ?>" alt="<?= $block->getData("banner_name") ?>" />
            <?php if($imgLink) : ?>
                </a>
            <?php endif; ?>

            <?php if($block->getData("button_1") || $block->getData("button_2")): ?>
                <div class="overlay">
                    <?php if($block->getData("button_link_1") && $block->getData("button_1")): ?>
                        <a class="btn btn-default btn-layer" href="<?= $block->getData("button_link_1") ?>">
                            <?= $block->getData("button_1") ?>
                        </a>
                    <?php endif; ?>
                    <?php if($block->getData("button_link_2") && $block->getData("button_2")): ?>
                        <a class="btn btn-default btn-layer" href="<?= $block->getData("button_link_2") ?>">
                            <?= $block->getData("button_2") ?>
                        </a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</section>
