<div class="row column-block three-columns-block">
    <div class="col col-sm-4">
        <div class="image_banner_wrap">
            <a class="image_link" href="<?= $block->getData("button_link_1") ?>">
                <img class="img-responsive" src="<?= $block->getData("photo1") ?>" alt="<?= $block->getData("title_1") ?>" />
            </a>
            <div class="overlay">
                <a class="btn btn-default" href="<?= $block->getData("button_link_1") ?>">
                    <?= $block->getData("button_1") ?>
                </a>
            </div>
        </div>
    </div>
    <div class="col col-sm-4">
        <div class="image_banner_wrap">
            <a class="image_link" href="<?= $block->getData("button_link_2") ?>">
                <img class="img-responsive" src="<?= $block->getData("photo2") ?>" alt="<?= $block->getData("title_2") ?>" />
            </a>
            <div class="overlay">
                <a class="btn btn-default" href="<?= $block->getData("button_link_2") ?>">
                    <?= $block->getData("button_2") ?>
                </a>
            </div>
        </div>
    </div>
    <div class="col col-sm-4">
        <div class="image_banner_wrap">
            <a class="image_link" href="<?= $block->getData("button_link_3") ?>">
                <img class="img-responsive" src="<?= $block->getData("photo3") ?>" alt="<?= $block->getData("title_3") ?>" />
            </a>
            <div class="overlay">
                <a class="btn btn-default" href="<?= $block->getData("button_link_3") ?>">
                    <?= $block->getData("button_3") ?>
                </a>
            </div>
        </div>
    </div>
</div>



