<div id="sizeChartHolder" style="display: none;">
    <div><strong><strong><span style="font-size: 1.17em;"></span></strong></strong>
        <h3 style="text-align: left;"><span style="font-size: x-small;">Please note: This is a general guide and not specific to individual items, unless stated otherwise.&nbsp;</span></h3>
    </div>
    <div>
        <p><span style="font-size: x-small;"></span></p>
        <h3></h3>
        <h3>Women's Tops &amp; Dresses&nbsp;</h3>
    </div>
    <div>
        <p dir="ltr">Tops, Dresses, Playsuits, Jackets, Sweats, Hoodies, Jumpers &amp; Cardigans</p>
        <table class="table_size">
            <tbody>
                <tr>
                    <td style="text-align: center;">AU</td>
                    <td style="text-align: center;" colspan="2">BUST</td>
                    <td style="text-align: center;" colspan="2">WAIST</td>
                    <td style="text-align: center;" colspan="2">HIPS</td>
                </tr>
                <tr>
                    <td style="text-align: center;">&nbsp;</td>
                    <td style="text-align: center;">IN</td>
                    <td style="text-align: center;">CM</td>
                    <td style="text-align: center;">IN</td>
                    <td style="text-align: center;">CM</td>
                    <td style="text-align: center;">IN</td>
                    <td style="text-align: center;">CM</td>
                </tr>
                <tr>
                    <td style="text-align: center;">6</td>
                    <td style="text-align: center;">31</td>
                    <td style="text-align: center;">79</td>
                    <td style="text-align: center;">24</td>
                    <td style="text-align: center;">61</td>
                    <td style="text-align: center;">35</td>
                    <td style="text-align: center;">89</td>
                </tr>
                <tr>
                    <td style="text-align: center;">8</td>
                    <td style="text-align: center;">33</td>
                    <td style="text-align: center;">84</td>
                    <td style="text-align: center;">26</td>
                    <td style="text-align: center;">66</td>
                    <td style="text-align: center;">37</td>
                    <td style="text-align: center;">94</td>
                </tr>
                <tr>
                    <td style="text-align: center;">10</td>
                    <td style="text-align: center;">35</td>
                    <td style="text-align: center;">89</td>
                    <td style="text-align: center;">28</td>
                    <td style="text-align: center;">71</td>
                    <td style="text-align: center;">39</td>
                    <td style="text-align: center;">99</td>
                </tr>
                <tr>
                    <td style="text-align: center;">12</td>
                    <td style="text-align: center;">37</td>
                    <td style="text-align: center;">94</td>
                    <td style="text-align: center;">30</td>
                    <td style="text-align: center;">76</td>
                    <td style="text-align: center;">41</td>
                    <td style="text-align: center;">104</td>
                </tr>
                <tr>
                    <td style="text-align: center;">14</td>
                    <td style="text-align: center;">39</td>
                    <td style="text-align: center;">99</td>
                    <td style="text-align: center;">32</td>
                    <td style="text-align: center;">81</td>
                    <td style="text-align: center;">
                        <p>43</p>
                    </td>
                    <td style="text-align: center;">109</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div></div>
    <div></div>
    <div>
        <h3>International Conversions</h3>
    </div>
    <div>
        <table class="table_size" border="0">
            <tbody>
                <tr>
                    <td style="text-align: center;">AU/UK</td>
                    <td style="text-align: center;">INT</td>
                    <td style="text-align: center;">US</td>
                    <td style="text-align: center;">EU</td>
                    <td style="text-align: center;">OTHER</td>
                </tr>
                <tr>
                    <td style="text-align: center;">6</td>
                    <td style="text-align: center;">XS</td>
                    <td style="text-align: center;">2</td>
                    <td style="text-align: center;">34</td>
                    <td style="text-align: center;">0</td>
                </tr>
                <tr>
                    <td style="text-align: center;">8</td>
                    <td style="text-align: center;">S</td>
                    <td style="text-align: center;">4</td>
                    <td style="text-align: center;">36</td>
                    <td style="text-align: center;">1</td>
                </tr>
                <tr>
                    <td style="text-align: center;">10</td>
                    <td style="text-align: center;">M</td>
                    <td style="text-align: center;">6</td>
                    <td style="text-align: center;">38</td>
                    <td style="text-align: center;">2</td>
                </tr>
                <tr>
                    <td style="text-align: center;">12</td>
                    <td style="text-align: center;">L</td>
                    <td style="text-align: center;">8</td>
                    <td style="text-align: center;">40</td>
                    <td style="text-align: center;">3</td>
                </tr>
                <tr>
                    <td style="text-align: center;">14</td>
                    <td style="text-align: center;">XL</td>
                    <td style="text-align: center;">10</td>
                    <td style="text-align: center;">42</td>
                    <td style="text-align: center;">4</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div></div>
    <h3>How to measure</h3>
    <p><span style="font-size: 12px;">To choose the correct size for you, measure your body as follows:</span></p>
    <p></p>
    <table class="measure">
        <tbody>
            <tr>
                <td>
                    <p>1. BUST
                        <br>Measure around fullest part</p>
                    <p>2. WAIST
                        <br>Measure around natural waistline</p>
                    <p>3. HIPS
                        <br>Measure 20cm down from the natural waistline</p>
                </td>
                <td><img src="https://d1cizyvjjqnss7.cloudfront.net/static/version1541969403/frontend/Pivotal/Peppermayo/en_US/Plumrocket_SizeChart/images/sizechart_womens_dresses.png" alt=""></td>
            </tr>
        </tbody>
    </table>
</div>
<button id="sizeChartTrigger">
<?php echo __('Size Guide') ?>
</button>

<script>
require(
[
  'jquery',
  'Magento_Ui/js/modal/modal'
],
function ($, modal) {
  var options = {
    type:       'popup',
    responsive: true,
    innersScroll: true,
    title:      'Size Guide',
    clickableOverlay: false,
    buttons:    [{
      text:  $.mage.__('Close'),
      class: '',
      click: function () {
        this.closeModal();
      }
    }]
  };

  $("#sizeChartTrigger").click(function () {

    $("#sizeChartHolder").modal(options).modal('openModal');
    return false;
  });
}
);
</script>
