<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Customer\Block\Link $block */
?>
<li class="link my-account hidden-xs">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <span class="label hidden"><?= $block->escapeHtml($block->getLabel()) ?></span>
        <i class="ppm-icon-member" aria-hidden="true"></i>
    </a>
</li>
