<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove $block */
?>

 <a href="#" data-role="remove" data-post-remove='<?php /* @escapeNotVerified */ echo $block->getItemRemoveParams($block->getItem()); ?>' title="<?php /* @escapeNotVerified */ echo __('Remove Item') ?>" class="btn-remove action delete">
    <span><i class="ppm-icon-close-circle" aria-hidden="true"></i> <?php /* @escapeNotVerified */ echo __('Delete');?></span>
</a>
